- name: Install eduroam Roaming Registry based on DjNRO
  hosts: djnro
  become: True
  vars_files:
    - group_vars/secrets.yml

  #Install Python2 on Ubuntu 16.04
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  # pre_tasks:
  #   # - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  #   - raw: test -e /usr/bin/python || (apt install -y python-minimal)
  #   - setup: # aka gather_facts

  roles:
    - apache
    - djnro
    - { role: shibboleth, when: enable_shibboleth == True }
    - { role: newrelic, when: enable_newrelic == True }
    - role: letsencrypt
      letsencrypt_webroot_path: "{{ installation_path }}"
      letsencrypt_email: "{{ admin_email }}"
      letsencrypt_cert_domains:
      - "{{ fqdn }}"
      letsencrypt_renewal_command_args: '--renew-hook "systemctl restart apache2"' 
