- include: install.yml

- name: Clone DjNRO repository
  git: repo=https://github.com/ubuntunet/djnro.git
       dest={{ installation_path }}
       force=yes
       version={{ github_branch }}

- name: Install Requirements
  pip: requirements={{ installation_path }}/requirements.txt

- name: Create PostgreSQL database
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:  name={{ db.name }}

- name: Create PostgreSQL user
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:  db={{ db.name }}
                    name={{ db.user }}
                    password={{ db_password }}
                    priv=ALL
                    role_attr_flags=NOCREATEDB,NOSUPERUSER

- name: Copy local settings
  template: src=local_settings.py.j2
            dest={{ installation_path }}/djnro/local_settings.py
            backup=yes

# - name: Setup DjNRO
#   django_manage: >
#     command=syncdb
#     app_path={{ installation_path }}

- name: Run migrations
  django_manage: >
    command=migrate
    app_path={{ installation_path }}

- name: Create Superuser
  django_manage: >
    command="createsuperuser --noinput --username={{ admin_user }} --email={{ admin_email }}" 
    app_path={{ installation_path }}
  ignore_errors: yes

- name: Collection static files
  django_manage: >
    command=collectstatic
    app_path={{ installation_path }}

- name: Fetch KML
  django_manage: >
    command=fetch_kml
    app_path={{ installation_path }}

- name: Copy front index
  template: src=front_index.html.j2
            dest={{ installation_path }}/djnro/templates/front/index.html

